baseurl = "https://akuhlens.github.io/"
title = "Weblog of a Computer Scientist"
theme = "academic"

# Enable comments by entering your Disqus shortname
disqusShortname = "akuhlens"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-88660385-1"

languageCode = "en-us"
canonifyurls = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  name = "Andre Kuhlenschmidt"
  role = "Computer Science PHD Student"
  organization = "Indiana University"
  avatar = "portrait.jpg"
  email = "<my github username>@indiana.edu"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = ""

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []


  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  # [[params.social]]
  #   icon = "envelope"
  #   icon_pack = "fa"
  #   link = "mailto:test@example.org"

  # [[params.social]]
  #   icon = "twitter"
  #   icon_pack = "fa"
  #   link = "//twitter.com/GeorgeCushen"

  # [[params.social]]
  #   icon = "google-scholar"
  #   icon_pack = "ai"
  #   link = "https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/akuhlens"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

# [[menu.main]]
#   name = "Publications"
#   url = "#publications_selected"
#   weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6


