baseurl = "https://akuhlens.github.io/"
title = "Weblog of a Computer Scientist"
theme = "academic"

languageCode = "en-us"
canonifyurls = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

